"""ALchemist LLM 辅助服务 — SSE 流式效应建议。

使用 .env 配置的 LLM 后端替代原 ~/.alchemist/config.json。
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import re
from itertools import combinations
from typing import AsyncGenerator

from app.core.config import settings
from app.core.logging import get_logger
from app.schemas.alchemist import SuggestEffectsRequest

logger = get_logger("poly_agent.alchemist_llm")

_SYSTEM_INSTRUCTIONS = """\
You are a scientific advisor for experimental design in chemistry and materials science.
Your task is to recommend which model terms (main effects, interactions, quadratic effects) \
are most scientifically justified for an optimal experimental design, based on domain \
knowledge and published literature.

IMPORTANT — effects selection: You must ONLY select effects from the provided \
"Available effects" list. Do not suggest effects that are not in the list. Do not invent \
or modify variable names. Select the minimum necessary set for a well-powered design — \
do not include effects you cannot justify scientifically.

CRITICAL — sources: Only cite references that appear verbatim in the "Literature context" \
section of the user message. If no "Literature context" section is present, you MUST return \
an empty sources array ([]). Never generate, guess, or invent citations. Fabricated \
references are significantly more harmful than an empty list.\
"""

_CONTROL_CHAR_RE = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")
_MAX_CONTEXT_LENGTH = 2000
_MAX_VARIABLE_NAME_LENGTH = 100

EFFECTS_SCHEMA: dict = {
    "type": "object",
    "properties": {
        "effects": {
            "type": "array",
            "description": "Selected effect strings taken verbatim from the available effects list.",
            "items": {"type": "string"},
        },
        "reasoning": {
            "type": "array",
            "description": "Scientific reasoning for each selected effect.",
            "items": {
                "type": "object",
                "properties": {
                    "effect": {"type": "string"},
                    "reason": {"type": "string"},
                },
                "required": ["effect", "reason"],
                "additionalProperties": False,
            },
        },
        "confidence": {
            "type": "array",
            "description": "Confidence level for each selected effect.",
            "items": {
                "type": "object",
                "properties": {
                    "effect": {"type": "string"},
                    "level": {"type": "string", "enum": ["high", "medium", "low"]},
                },
                "required": ["effect", "level"],
                "additionalProperties": False,
            },
        },
        "sources": {
            "type": "array",
            "description": "Literature sources. ONLY include citations from the Literature context section.",
            "items": {"type": "string"},
        },
        "disclaimer": {
            "type": "string",
            "description": "Standard disclaimer about the AI-generated nature of these recommendations.",
        },
    },
    "required": ["effects", "reasoning", "confidence", "sources", "disclaimer"],
    "additionalProperties": False,
}

_DEFAULT_DISCLAIMER = (
    "These recommendations are generated by an AI model and should be reviewed by "
    "a domain expert. Sources should be independently verified before citation."
)


def _sanitize_text(text: str, max_length: int) -> str:
    cleaned = _CONTROL_CHAR_RE.sub("", text)
    if len(cleaned) > max_length:
        cleaned = cleaned[:max_length] + "…"
    return cleaned


def _sanitize_variable_name(name: str) -> str:
    return _sanitize_text(name, _MAX_VARIABLE_NAME_LENGTH)


def _format_variable(v: dict) -> str:
    vtype = v.get("type", "real")
    name = _sanitize_variable_name(v["name"])
    if vtype == "categorical":
        cats = v.get("categories", v.get("values", []))
        return f"- {name} (categorical): {cats}"
    lo = v.get("lower_bound", v.get("min", "?"))
    hi = v.get("upper_bound", v.get("max", "?"))
    unit = v.get("unit") or ""
    unit_str = f" {unit}" if unit else ""
    return f"- {name} ({vtype}): {lo}–{hi}{unit_str}"


def _build_effects_lists(variables: list[dict]) -> tuple[list[str], list[str], list[str]]:
    cont_types = {"real", "integer", "discrete", None}
    all_names = [_sanitize_variable_name(v["name"]) for v in variables]
    cont_names = [_sanitize_variable_name(v["name"]) for v in variables if v.get("type") in cont_types]
    interactions = [f"{a}*{b}" for a, b in combinations(all_names, 2)]
    quadratics = [f"{n}**2" for n in cont_names]
    return all_names, interactions, quadratics


def build_user_prompt(
    variables: list[dict],
    system_context: str,
    literature_context: str | None = None,
) -> str:
    main, interactions, quadratics = _build_effects_lists(variables)
    var_lines = "\n".join(_format_variable(v) for v in variables)
    safe_context = _sanitize_text(system_context, _MAX_CONTEXT_LENGTH)

    lit_section = ""
    if literature_context:
        lit_section = f"\nLiterature context (retrieved from scientific database):\n{literature_context}\n"

    interactions_str = ", ".join(interactions) if interactions else "(none)"
    quadratics_str = ", ".join(quadratics) if quadratics else "(none)"

    return (
        f"System description: {safe_context}"
        f"{lit_section}\n"
        f"Variable space:\n{var_lines}\n\n"
        f"Available effects to select from:\n"
        f"  Main effects:    {', '.join(main)}\n"
        f"  Interactions:    {interactions_str}\n"
        f"  Quadratic:       {quadratics_str}\n\n"
        f"Recommend which effects are most likely to be scientifically significant "
        f"for this system{' based on the literature context above' if literature_context else ''}."
    )


def build_edison_query(variables: list[dict], system_context: str) -> str:
    var_desc = "; ".join(
        f"{_sanitize_variable_name(v['name'])} ({v.get('type', 'real')})" for v in variables
    )
    safe_context = _sanitize_text(system_context, _MAX_CONTEXT_LENGTH)
    return (
        f"What main effects, interactions, and quadratic/curvature terms are "
        f"scientifically significant for the following experimental system?\n\n"
        f"System: {safe_context}\n\n"
        f"Variables: {var_desc}\n\n"
        f"Specifically: (1) Which variables most strongly affect the target response? "
        f"(2) Which pairwise interactions are likely important? "
        f"(3) Which variables likely show non-linear (quadratic/curvature) behavior? "
        f"Please cite specific literature sources where possible."
    )


def _get_structuring_provider(config):
    """根据请求中的 provider 配置创建 LLM 客户端。

    优先使用请求中的 api_key，回退到 .env 的 LLM_API_KEY。
    """
    provider = config.provider
    api_key = config.api_key or settings.llm_api_key
    base_url = config.base_url or settings.llm_base_url
    model = config.model or settings.llm_model

    if provider == "openai":
        from app.services.alchemist_providers.openai_provider import OpenAIProvider
        return OpenAIProvider(api_key=api_key, model=model)

    if provider == "ollama":
        from app.services.alchemist_providers.ollama_provider import OllamaProvider
        url = (base_url or "http://localhost:11434").rstrip("/")
        if not url.endswith("/v1"):
            url = url + "/v1"
        return OllamaProvider(model=model, base_url=url)

    raise ValueError(f"Unknown structuring provider: {provider!r}")


def _sse(data: dict) -> str:
    return f"data: {json.dumps(data)}\n\n"


async def suggest_effects_stream(
    variables: list[dict],
    request: SuggestEffectsRequest,
) -> AsyncGenerator[str, None]:
    """SSE 流式返回 LLM 效应建议。

    Yields:
        SSE 事件字符串，终止事件 status 为 "complete" 或 "error"。
    """
    literature_context: str | None = None

    # Stage 1: 可选文献搜索
    if request.edison_config:
        try:
            from app.services.alchemist_providers.edison_provider import EdisonLiteratureProvider

            edison_key = request.edison_config.api_key or settings.edison_api_key
            edison = EdisonLiteratureProvider(api_key=edison_key, job_type=request.edison_config.job_type)
            query = build_edison_query(variables, request.system_context)

            yield _sse({"status": "searching_literature", "message": "正在搜索文献…", "trajectory_url": ""})
            task_id = await edison.start_search(query)
            trajectory_url = edison.get_trajectory_url(task_id)

            timeout_secs = request.edison_config.timeout_secs or 1200
            loop_start = asyncio.get_event_loop().time()

            while True:
                await asyncio.sleep(30)
                elapsed = int(asyncio.get_event_loop().time() - loop_start)
                if elapsed >= timeout_secs:
                    yield _sse({"status": "literature_error", "message": "文献搜索超时，跳过"})
                    break
                task_result = await edison.poll_task(task_id)
                if getattr(task_result, "status", None) == "success":
                    answer = getattr(task_result, "answer", "")
                    formatted_answer = getattr(task_result, "formatted_answer", "")
                    has_answer = getattr(task_result, "has_successful_answer", False)
                    if has_answer and formatted_answer:
                        literature_context = formatted_answer
                        yield _sse({
                            "status": "literature_complete",
                            "message": "文献搜索完成",
                            "trajectory_url": trajectory_url,
                            "cached": False,
                        })
                    else:
                        yield _sse({
                            "status": "literature_warning",
                            "message": "文献搜索未找到确定结果",
                            "trajectory_url": trajectory_url,
                            "cached": False,
                        })
                    break
                yield _sse({
                    "status": "searching_literature_progress",
                    "message": f"文献搜索进行中… ({elapsed // 60}m {elapsed % 60}s)",
                    "trajectory_url": trajectory_url,
                })
        except Exception as exc:
            yield _sse({"status": "literature_error", "message": f"文献搜索失败: {exc}"})

    # Stage 2: 结构化 LLM 调用
    provider_label = f"{request.structuring_provider.provider}/{request.structuring_provider.model or settings.llm_model}"
    yield _sse({"status": "structuring", "message": f"调用 {provider_label} 提取效应建议…"})

    try:
        provider = _get_structuring_provider(request.structuring_provider)
        user_prompt = build_user_prompt(variables, request.system_context, literature_context)
        result = await provider.suggest_effects(_SYSTEM_INSTRUCTIONS, user_prompt, EFFECTS_SCHEMA)

        result.setdefault("effects", [])
        result.setdefault("reasoning", [])
        result.setdefault("confidence", [])
        result.setdefault("sources", [])
        result.setdefault("disclaimer", _DEFAULT_DISCLAIMER)
        result["literature_context"] = literature_context

        yield _sse({"status": "complete", "result": result})
    except Exception as exc:
        yield _sse({"status": "error", "message": str(exc)})
