// 垂类模型（接口配置）示例场景。
// 用于接口配置向导“一键填入示例”：把表单预填成可教学的配置。
// 仅预填技术字段；开发者、机构、来源 URL、Logo 等归属字段一律留空，
// 由用户按真实模型填写（归属展示规范见 doc/polyagent-attribution-source-matrix.md）。

export const INTERFACE_CONFIG_EXAMPLES = [
  {
    id: 'fastapi_smiles',
    title: 'FastAPI 单分子性质预测',
    description: '本地 Demo 服务的 POST JSON 调用，演示“SMILES 进、数值出”。',
    tags: ['FastAPI', '可本地运行'],
    form: {
      algorithm_id: 'remote_smiles_property_predictor',
      name: 'Remote SMILES Property Predictor',
      version: '0.1.0',
      protocol: 'fastapi',
      endpoint_url: 'http://127.0.0.1:8301/predict',
      http_method: 'POST',
      timeout_seconds: 30,
      response_selector: 'data.prediction',
      description: '通过远程 FastAPI 服务预测分子性质（Demo 教学示例，请替换为真实服务）。',
      visibility: 'private',
      sample_input: { smiles: 'CCO' },
    },
    input_fields: [{ name: 'smiles', type: 'string', required: true, unit: '' }],
    output_fields: [{ name: 'prediction', type: 'number', required: true, unit: 'K' }],
    query_bindings: {},
    header_bindings: {},
    static_headers: {},
    secret_refs: {},
    notes: [
      '先在本地启动 examples/interface_config/demo_service（端口 8301），即可直接保存并完成样例测试。',
      '正式接入时把 endpoint 替换为生产 HTTPS 地址。',
    ],
  },
  {
    id: 'http_batch',
    title: 'HTTP 批量配方预测',
    description: '适合批量列表输入，演示“列表进、列表出”的 HTTP 接入。',
    tags: ['HTTP', '批量'],
    form: {
      algorithm_id: 'remote_batch_formulation_predictor',
      name: 'Remote Batch Formulation Predictor',
      version: '0.1.0',
      protocol: 'http',
      endpoint_url: 'https://your-service.example.com/predict',
      http_method: 'POST',
      timeout_seconds: 60,
      response_selector: 'data.results',
      description: '批量配方远程预测接口（Demo 教学示例，endpoint 为占位地址）。',
      visibility: 'private',
      sample_input: {
        formulations: [
          {
            formula_id: 'TEST-001',
            task_type: 'electrolyte',
            lithium_salt: 'LiTFSI',
            lithium_salt_mol_L: 1.0,
            electrolyte_component_1: 'FEC',
            electrolyte_component_1_mol_ratio: 1,
            electrolyte_component_2: 'DME',
            electrolyte_component_2_mol_ratio: 1,
          },
        ],
      },
    },
    input_fields: [{ name: 'formulations', type: 'list', required: true, unit: '' }],
    output_fields: [{ name: 'results', type: 'list', required: true, unit: '' }],
    query_bindings: {},
    header_bindings: {},
    static_headers: {},
    secret_refs: {},
    notes: [
      '将 endpoint 替换为你的真实服务地址，并确保响应结构与响应提取路径一致。',
      '批量场景一般建议将超时调到 30-60 秒。',
    ],
  },
  {
    id: 'http_get_binding',
    title: 'GET 查询参数绑定',
    description: '把输入字段映射为 URL 查询参数，适配无请求体的接口。',
    tags: ['GET', 'Query 绑定'],
    form: {
      algorithm_id: 'remote_get_smiles_predictor',
      name: 'Remote GET SMILES Predictor',
      version: '0.1.0',
      protocol: 'http',
      endpoint_url: 'http://127.0.0.1:8301/predict',
      http_method: 'GET',
      timeout_seconds: 30,
      response_selector: 'data.prediction',
      description: '通过 GET 查询参数调用远程预测接口（Demo 教学示例，请替换为真实服务）。',
      visibility: 'private',
      sample_input: { smiles: 'CCO' },
    },
    input_fields: [{ name: 'smiles', type: 'string', required: true, unit: '' }],
    output_fields: [{ name: 'prediction', type: 'number', required: true, unit: 'K' }],
    query_bindings: { smiles: 'smiles' },
    header_bindings: {},
    static_headers: {},
    secret_refs: {},
    notes: [
      'Query 绑定把已声明的输入字段映射为 URL 参数，如 smiles → ?smiles=CCO。',
      '认证相关参数不能通过普通 Query 绑定传入，必须使用环境变量或密钥引用。',
    ],
  },
  {
    id: 'auth_header_secret',
    title: '带鉴权的接口接入',
    description: '通过密钥引用注入 Authorization 头，平台不保存明文。',
    tags: ['密钥引用', '鉴权'],
    form: {
      algorithm_id: 'remote_authed_property_predictor',
      name: 'Remote Authed Property Predictor',
      version: '0.1.0',
      protocol: 'fastapi',
      endpoint_url: 'http://127.0.0.1:8301/predict',
      http_method: 'POST',
      timeout_seconds: 30,
      response_selector: 'data.prediction',
      description: '需要 Bearer 鉴权的远程预测接口（Demo 教学示例，请替换为真实服务）。',
      visibility: 'private',
      sample_input: { smiles: 'CCO' },
    },
    input_fields: [{ name: 'smiles', type: 'string', required: true, unit: '' }],
    output_fields: [{ name: 'prediction', type: 'number', required: true, unit: 'K' }],
    query_bindings: {},
    header_bindings: {},
    static_headers: {},
    secret_refs: { Authorization: 'MODEL_API_TOKEN' },
    notes: [
      '密钥引用名只能使用大写字母、数字或下划线；平台只保存引用名，不保存密钥值。',
      'demo 服务设置 DEMO_API_TOKEN 环境变量后即要求 Bearer 鉴权，可配合此场景联调。',
    ],
  },
  {
    id: 'mcp_preview',
    title: 'MCP 接口（仅配置）',
    description: '演示 MCP 协议配置边界：可保存，暂不支持测试与激活。',
    tags: ['MCP', '预览'],
    form: {
      algorithm_id: 'remote_mcp_property_predictor',
      name: 'Remote MCP Property Predictor',
      version: '0.1.0',
      protocol: 'mcp',
      endpoint_url: 'https://mcp.example.com/rpc',
      http_method: 'POST',
      timeout_seconds: 30,
      response_selector: '',
      description: 'MCP 协议接口配置（Demo 教学示例，仅用于了解配置边界）。',
      visibility: 'private',
      sample_input: { smiles: 'CCO' },
    },
    input_fields: [{ name: 'smiles', type: 'string', required: true, unit: '' }],
    output_fields: [{ name: 'prediction', type: 'number', required: true, unit: 'K' }],
    query_bindings: {},
    header_bindings: {},
    static_headers: {},
    secret_refs: {},
    notes: [
      'MCP 保存后不可进行样例测试和激活，调用会返回 REMOTE_PROTOCOL_NOT_SUPPORTED。',
      '此场景用于熟悉协议边界，实际接入请选择 HTTP 或 FastAPI。',
    ],
  },
]

export function findInterfaceExample(exampleId) {
  return INTERFACE_CONFIG_EXAMPLES.find((item) => item.id === exampleId) || null
}
